parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): 'mysql://qerj1c7wj6jp4egb:spwx9g94hy1v1ri0@q7cxv1zwcdlw7699.chr7pe7iynqr.eu-west-1.rds.amazonaws.com:3306/e8d552v74xues8a9'

doctrine:
    dbal:
        # configure these for your database server
        driver: 'mysql'
        host:     'q7cxv1zwcdlw7699.chr7pe7iynqr.eu-west-1.rds.amazonaws.com'
        username: 'qerj1c7wj6jp4egb'
        password: '	spwx9g94hy1v1ri0'
        port: 3306
        database: 'e8d552v74xues8a9'
        server_version: '5.6'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
